baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Dat N. Stories"
theme: hugo-profile

# Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: dropdown
      name: Blog
      weight: 1
    - identifier: dropdown1
      name: Blogs
      url: /blogs
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      name: Tags
      url: /tags
      parent: dropdown
      weight: 1

params:
  title: "Dat N. Stories"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/logo.png"  

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #  menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Dat N."
    subtitle: "I build better myself for better future"
    content: '"Life isn’t about finding yourself. Life is about creating yourself." ― George Bernard Shaw'
    image: /images/hero.png
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/hudavn
        - icon: fab fa-facebook
          url: https://facebook.com/iamhudaaaaa
        - icon: fab fa-instagram
          url: https://instagram.com/datng__


  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am an Data Engineer with background in Data Science and Competitive Programming. Very instered in technology and sport. 
      
      Currently working as a Fresher Software Developement at [ZaloPay](https://zalopay.vn) and Algorithm lecturer & Data Analyst TA at [MindX](https://mindx.vn)

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Scala"
        - "Flutter"
        - "ReactJS"
        - "JavaScript"
        - "C/C++"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Vietnam Olympiad for Informatics in 2019
        content: I got Third Prize with the highest score among the same-prize participants, just a little short for me to get Second Prize.
      - title: April 30 Olympiad in 2017 
        content: I won a Bronze medal in the annual contest for specialized schools in the central and southern regions of Vietnam.
      - title: Northern Coastal and Plains Olympiads in 2018
        content: I won a Silver medal.
      - title: Other contests
        content: I have participated in many other competitions to practice and improve myself, and have also achieved many remarkable achievements.
  # projects
  projects:
    enable: true
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: ddforwork08@gmail.com
    btnName: Send me an email

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/hudavn 
      instagram: https://instagram.com/datng__
      facebook: https://facebook.com/iamhudaaaaa
