baseURL: "https://hudavn.github.io"
languageCode: "en-us"
title: "Dat N. Stories"
theme: hugo-profile

# Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: dropdown
      name: Blog
      weight: 1
    - identifier: dropdown1
      name: Blogs
      url: /blogs
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      name: Tags
      url: /tags
      parent: dropdown
      weight: 1

params:
  title: "Dat N. Stories"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/logo.png"  

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #  menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Dat N."
    subtitle: "I build better myself for better future"
    content: '"Life isn’t about finding yourself. Life is about creating yourself." ― George Bernard Shaw'
    image: /images/hero.png
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/hudavn
        - icon: fab fa-facebook
          url: https://facebook.com/iamhudaaaaa
        - icon: fab fa-instagram
          url: https://instagram.com/datng__


  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am an Data Engineer with background in Data Science and Competitive Programming. Very instered in technology and sports. 
      
      Currently working as a Fresher Software Developement at [ZaloPay](https://zalopay.vn) and Algorithm Lecturer & Data Analyst TA at [MindX](https://mindx.vn)

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Scala"
        - "PowerBI"
        - "MySQL/MSSQL"
        - "Flutter"
        - "JavaScript"
        - "Solidity"
        - "C/C++"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Vietnam Olympiad for Informatics in 2019
        content: I got Third Prize with the highest score among the same-prize participants, just a little short for me to get Second Prize.
      - title: April 30 Olympiad in 2017 
        content: I won a Bronze medal in the annual contest for specialized schools in the central and southern regions of Vietnam.
      - title: Other contests
        content: I have participated in many other competitions to practice and improve myself, and have also achieved many remarkable achievements.
  # projects
  projects:
    enable: true
    items:
      - title: Credit Card Fraud Detection
        content: Anonymized credit card transactions labeled as fraudulent or genuine
        image: /images/projects/credit_card_fraud.png
        badges:
          - "Fraud Detection"
          - "Classification"
          - "Machine Learning"
          - "Python"
          - "Data Science"
        links:
          - icon: fab fa-github
            url: https://github.com/hudavn/credit-card-fraud

      - title: Lead Generation - Podcast Guests
        content: People who are guest in podcasts about Business on iTunes  
        image: /images/projects/lead_generation.png
        badges:
          - "Python"
          - "Natural Language Processing"
          - "Web Scraping"
          - "Selenium"
        links:
          - icon: fab fa-github
            url: https://github.com/hudavn/PodcastGuests

      - title: Smart Contract - Wave Portal
        content: Smart contract on Ethereum that allow people interacting with it by connect to wallet then send transactions as waves to me.
        image: /images/projects/smart-contract.png
        badges:
          - "Solidity"
          - "JavaScript"
          - "Smart Contract"
          - "Ethereum"
          - "Blockchain"
        links:
          - icon: fab fa-github
            url: https://github.com/hudavn/wave-portal-sc

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: ddforwork08@gmail.com
    btnName: Send me an email

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/hudavn 
      instagram: https://instagram.com/datng__
      facebook: https://facebook.com/iamhudaaaaa
